/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as LiquidityRouteImport } from './routes/liquidity'
import { Route as FarmingRouteImport } from './routes/farming'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CasinoRouteImport } from './routes/casino'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasinoAdminRouteImport } from './routes/casino.admin'
import { Route as ApiAiAgentRouteImport } from './routes/api/ai-agent'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidityRoute = LiquidityRouteImport.update({
  id: '/liquidity',
  path: '/liquidity',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmingRoute = FarmingRouteImport.update({
  id: '/farming',
  path: '/farming',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoRoute = CasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoAdminRoute = CasinoAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CasinoRoute,
} as any)
const ApiAiAgentRoute = ApiAiAgentRouteImport.update({
  id: '/api/ai-agent',
  path: '/api/ai-agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/casino': typeof CasinoRouteWithChildren
  '/docs': typeof DocsRoute
  '/farming': typeof FarmingRoute
  '/liquidity': typeof LiquidityRoute
  '/pools': typeof PoolsRoute
  '/portfolio': typeof PortfolioRoute
  '/swap': typeof SwapRoute
  '/api/ai-agent': typeof ApiAiAgentRoute
  '/casino/admin': typeof CasinoAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/casino': typeof CasinoRouteWithChildren
  '/docs': typeof DocsRoute
  '/farming': typeof FarmingRoute
  '/liquidity': typeof LiquidityRoute
  '/pools': typeof PoolsRoute
  '/portfolio': typeof PortfolioRoute
  '/swap': typeof SwapRoute
  '/api/ai-agent': typeof ApiAiAgentRoute
  '/casino/admin': typeof CasinoAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/casino': typeof CasinoRouteWithChildren
  '/docs': typeof DocsRoute
  '/farming': typeof FarmingRoute
  '/liquidity': typeof LiquidityRoute
  '/pools': typeof PoolsRoute
  '/portfolio': typeof PortfolioRoute
  '/swap': typeof SwapRoute
  '/api/ai-agent': typeof ApiAiAgentRoute
  '/casino/admin': typeof CasinoAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/casino'
    | '/docs'
    | '/farming'
    | '/liquidity'
    | '/pools'
    | '/portfolio'
    | '/swap'
    | '/api/ai-agent'
    | '/casino/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/casino'
    | '/docs'
    | '/farming'
    | '/liquidity'
    | '/pools'
    | '/portfolio'
    | '/swap'
    | '/api/ai-agent'
    | '/casino/admin'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/casino'
    | '/docs'
    | '/farming'
    | '/liquidity'
    | '/pools'
    | '/portfolio'
    | '/swap'
    | '/api/ai-agent'
    | '/casino/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CasinoRoute: typeof CasinoRouteWithChildren
  DocsRoute: typeof DocsRoute
  FarmingRoute: typeof FarmingRoute
  LiquidityRoute: typeof LiquidityRoute
  PoolsRoute: typeof PoolsRoute
  PortfolioRoute: typeof PortfolioRoute
  SwapRoute: typeof SwapRoute
  ApiAiAgentRoute: typeof ApiAiAgentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidity': {
      id: '/liquidity'
      path: '/liquidity'
      fullPath: '/liquidity'
      preLoaderRoute: typeof LiquidityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farming': {
      id: '/farming'
      path: '/farming'
      fullPath: '/farming'
      preLoaderRoute: typeof FarmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino': {
      id: '/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof CasinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino/admin': {
      id: '/casino/admin'
      path: '/admin'
      fullPath: '/casino/admin'
      preLoaderRoute: typeof CasinoAdminRouteImport
      parentRoute: typeof CasinoRoute
    }
    '/api/ai-agent': {
      id: '/api/ai-agent'
      path: '/api/ai-agent'
      fullPath: '/api/ai-agent'
      preLoaderRoute: typeof ApiAiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CasinoRouteChildren {
  CasinoAdminRoute: typeof CasinoAdminRoute
}

const CasinoRouteChildren: CasinoRouteChildren = {
  CasinoAdminRoute: CasinoAdminRoute,
}

const CasinoRouteWithChildren =
  CasinoRoute._addFileChildren(CasinoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CasinoRoute: CasinoRouteWithChildren,
  DocsRoute: DocsRoute,
  FarmingRoute: FarmingRoute,
  LiquidityRoute: LiquidityRoute,
  PoolsRoute: PoolsRoute,
  PortfolioRoute: PortfolioRoute,
  SwapRoute: SwapRoute,
  ApiAiAgentRoute: ApiAiAgentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
